providers = ['php', 'node']

[variables]
NIXPACKS_NODE_VERSION = '20'

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm ci',
]

[phases.build]
cmds = [
    'npm run build',
]

[start]
cmd = 'bash railway-start.sh'
