[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bash railway-start.sh"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/prisijungti"
healthcheckTimeout = 60
